language: haskell
install:
  - "cabal install -v3 --dry-run --enable-tests"
script:
  - "cabal install --enable-tests --jobs=1"
  - "cabal test"
notifications:
  email:
    on_success: never
    on_failure: change
